name: Swift

on: [push]

jobs:
  tests:
    name: Unit Tests
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - name: Setup Xcode version
      uses: maxim-lobanov/setup-xcode@v1.6.0
      with:
          xcode-version: '15.0.1'
    - name: Build
      run: swift test --enable-code-coverage
